require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'config/environments/*.rb'
    - 'bin/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

RSpec/AnyInstance:
  Enabled: false